apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: my-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: kubernetes-nodejs
  template:
    metadata:
      labels:
        app: kubernetes-nodejs
    spec:
      containers:
        - name: my-app-container
          image: missdoo/kubernetes:master-493cf648550a3a617ab0c120e861636a5228e0ee
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
