name: Build, Push, and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set env
        run: echo "GITHUB_BRANCH=$(echo $GITHUB_REF_NAME-$GITHUB_SHA)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx inspect default --bootstrap
          docker buildx build --file Dockerfile -t missdoo/kubernetes:$GITHUB_BRANCH --load .

      - name: Push Docker image to Docker Hub
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username missdoo --password-stdin
          docker push missdoo/kubernetes:$GITHUB_BRANCH

      - name: Update manifest file
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git remote add upstream https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/DennieDan/kubernetes-nodejs.git
          yq eval '.spec.template.spec.containers[0].image = "missdoo/kubernetes:${{ env.GITHUB_BRANCH }}"' -i deployments/deployment.yml
          git add deployments/deployment.yml
          git commit -m "Updating newer image to $GITHUB_BRANCH"
          git pull --rebase upstream master
          git push upstream master
